### ISSUE TITLE
treeModel undefined when test angular-tree-component

### ISSUE THREAD

**Issue by xzegga** [CirclonGroup/angular-tree-component#724]
I am trying to make a unit test for treeModel update method but I am getting undefined in my test. can you check this question on stackoverflow and help me?

[treemodel-undefined-when-test-angular-tree-component](https://stackoverflow.com/questions/56032721/treemodel-undefined-when-test-angular-tree-component)

**Comment by soczysty7** [comment]
Wrapping test inside fakeAsync zone worked for me in similar case (calling component method which called treeModel's expandAll). I had to add tick(100) to wait for async nodes to load.

**Comment by tobiasengelhardt** [comment]
We also use fakeAsync for our unit tests of the tree component. We are in the process of reworking the documentation and how to unit test will also be a part of that. Will close this for now.
