### ISSUE TITLE
How to add Tool tip for each tree attribute in angular tree component

### ISSUE THREAD

**Issue by sunilkumar8609** [CirclonGroup/angular-tree-component#730]
how to add ToolTip to angular tree component?

**Comment by Js4Life** [comment]
answers pls

**Comment by Prabukmca** [comment]
Did you get the answer? How did you achieved this?

**Comment by tobiasengelhardt** [comment]
@Js4Life @Prabukmca 

You can use the custom template for this. Take a look at the [documentation](https://angular2-tree.readme.io/docs/templates). With this you can style a node of the tree. There you can do what you like - including adding a ToolTip.

Example:
```
<tree-root [nodes]="nodes">
  <ng-template #treeNodeTemplate let-node let-index="index">
    <div [title]="node.data.toolTip">{{ node.data.name }}</div>
  </ng-template>
</tree-root>
```

But the template gives you also the freedom to include other implemenations like the material or ngx-bootstrap tooltips.

Closing this for now. If there are other questions please open a new issue. Thanks
