### ISSUE TITLE
incorrect peer dependency "core-js@^2.4.1" 

### ISSUE THREAD

**Issue by mshariq-nerd** [CirclonGroup/angular-tree-component#766]
Getting incorrect peer dependency warning while updating angular-tree-component version 
`warning " > angular-tree-component@8.4.1" has incorrect peer dependency "core-js@^2.4.1".`

**Comment by nacrotic** [comment]
Same for me in 8.5.2 while core-js is in 3.2.1

**Comment by tobiasengelhardt** [comment]
`core-js` is not a peer dependency anymore starting with version `10.0.0` of the tree. If you update from version `8` of the tree update the tree dependency from `angular-tree-component` to `@circlon/angular-tree-component` and take a look in the changelog to see the changes.
Closing this issue. Please open a new issue if the problem still exists.
