### ISSUE TITLE
Angular 9- Angular Tree Component Postinstall Fails with ngcc

### ISSUE THREAD

**Issue by rahulroykumar** [CirclonGroup/angular-tree-component#796]
PLEASE READ CAREFULLY!

# Reproduce
Please reproduce here if reporting a bug, or requesting help:
https://stackblitz.com/edit/angular-wxansn

# Additional Info
 "dependencies": {
    "@angular/animations": "9.0.0",
    "@angular/cdk": "9.0.0",
    "@angular/cli": "^9.0.0",
    "@angular/common": "9.0.0",
    "@angular/forms": "9.0.0",
    "@angular/material": "9.0.0",
    "@angular/platform-browser": "9.0.0",
    "@angular/platform-browser-dynamic": "9.0.0",
    "@angular/router": "9.0.0",
    "@types/c3": "^0.7.3",
    "@types/node": "^13.1.7",
    "ag-grid": "17.1.1",
    "ag-grid-angular": "17.1.0",
    "ag-grid-enterprise": "17.1.1",
    "angular-tree-component": "8.5.6",
    "applicationinsights-js": "~1.0.20",
    "c3": "^0.7.8",
    "core-js": "3.3.5",
    "create-hash": "1.2.0",
    "crypto-browserify": "~3.12.0",
    "d3": "^5.12.0",
    "hammerjs": "~2.0.8",
    "increase-memory-limit": "^1.0.7",
    "lodash": "~4.17.15",
    "lowlight": "^1.12.1",
    "moment": "~2.24.0",
    "powerbi-client": "2.8.0",
    "rehype": "^9.0.0",
    "rxjs": "6.5.3",
    "rxjs-compat": "6.5.3",
    "zone.js": "0.9.1"
  },
  "peerDependencies": {
    "@angular/compiler": "9.0.0",
    "@angular/core": "9.0.0"
  },
Chrome
with "postinstall": "ngcc" it works fine but
Tree component fails when using below postinstall script:

ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"

![image](https://user-images.githubusercontent.com/8906476/74856667-584c0c00-52f7-11ea-8922-ebc2b8c14844.png)

can you please suggest? I need to create ivy entry points

# Use the Slack Channel
The fastest way to get an answer is via the slack channel:
https://angular-tree-component.herokuapp.com/

You will also get updates on releases, bugfixes and other announcements.

# Search Docs First
Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

**Comment by rahulroykumar** [comment]
I see that a similar problem was resolved in below issue:
https://github.com/500tech/angular-tree-component/pull/771

Referring to below issue 
https://github.com/angular/angular/issues/33685
I removed "main": "dist/angular-tree-component.umd.js", in node_modules/angular-tree-component/package.json and it worked fine.


Can someone please suggest a permanent fix?

**Comment by rahulroykumar** [comment]
@adamkleingit 

Can you please help?

**Comment by danigiri** [comment]
I am experiencing the same issue when invoking `ng serve`

**Comment by danigiri** [comment]
I am also seeing `ERROR in dist/components/tree.component.d.ts:1:21 - error TS2724: Module '"../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?`

Which is one of the changes that the Angular 9 updater will do for you

**Comment by rahulroykumar** [comment]
@danigiri 

Which version of angular-tree-component are you using?

**Comment by danigiri** [comment]
@rahulroykumar good point, I'll double check the version

**Comment by danigiri** [comment]
Discard my comment, was actually using a much older version than I realised, thanks for the hint

**Comment by olivierboudet** [comment]
I have only this issue as soon as I add the `--first-only` flag.

**Comment by debender495** [comment]
@rahulroykumar try adding "skipLibCheck": true , as below in tsconfig.json

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "importHelpers": true,
    "module": "esnext",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "skipLibCheck": true
  }
}

**Comment by destrigot** [comment]
I found a solution that may work.

1.  Open your package.json and delete the ' "postinstall": "ngcc" '
2.  Delete the node_modules folder
3.  Run npm install
4.  Run your ng serve or ng build

ngcc will be executed before compile for IVY, for some reason which I dont know yet, if ngcc run at this time and not after the npm install, it precompiles properly the module and then its readable for IVY.

Another issue you may face is that it actually compiles the library twice and the second one fails, but after it end to precompile all the modules for ivy, it will try again and succeed.

I hope it helps.

Where is the owner of the project? is he still alive? why don't you give right to people who care about this library?

**Comment by tobiasengelhardt** [comment]
The ownership of the project changed last week. Adam will still help out because he knows the tree component the best. Updating the tree to Angular 9 is on top of the list. We need this for our projects as well. There should be an updated version (or at least a release candidate) within the next 2 weeks.

**Comment by tobiasengelhardt** [comment]
Closing this because now there is an Angular 9 version of the tree. Please use v9.0.2 (or newer if available).
Please note that the package name changed from `angular-tree-component` to `@circlon/angular-tree-component`. We tried to keep the old name but couldn't transfer the publishing rights. This requires some path changes after the update. Take a look at the changelog to see the changes.

Please open a new issue if the problem still exists.
