### ISSUE TITLE
Please add license in NPM package

### ISSUE THREAD

**Issue by Rajdeep97** [CirclonGroup/angular-tree-component#842]
Please add license in your new NPM page:
https://www.npmjs.com/package/@circlon/angular-tree-component/v/9.0.2

As this is a open source project under MIT license, without a proper listing it is difficult to use in a corporate environment.
Thank You!

**Comment by tobiasengelhardt** [comment]
@Rajdeep97 thanks for catching this! Now the license is correctly shown in the listing on npmjs.
