### ISSUE TITLE
Providing a custom loadingTemplate leads to ExpressionChangedAfterItHasBeenCheckedError in Ivy

### ISSUE THREAD

**Issue by Cowraider** [CirclonGroup/angular-tree-component#853]
## I'm submitting a...

<pre><code>
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the current behavior?

Providing a custom _loadingTemplate_  (see [https://angular2-tree.readme.io/docs/templates#loadingtemplate](https://angular2-tree.readme.io/docs/templates#loadingtemplate)) within a _treeNodeFullTemplate_ leads to an `ExpressionChangedAfterItHasBeenCheckedError `. 

## Expected behavior:

The `ExpressionChangedAfterItHasBeenCheckedError`should not occur when providing a custom loadingTemplate or it should be documented if it must not be provided in combination with a _treeNodeFullTemplate_.

## Minimal reproduction of the problem with instructions:

Just open the following link:
[Stackblitz link for reproduction](https://stackblitz.com/edit/angular-ivy-2ggzzd)

In the console you can see the error showing up. 

## Version of affected browser(s),operating system(s), npm, node and angular-tree-component:

Tested with 

- angular-tree-component version 10.0.0 and angular version 10.0.1
- angular-tree-component version 9.0.3 and angular version 9.1.12

## Other information:

When disabling the ivy compiler this error does not occur.

**Comment by Cowraider** [comment]
I checked out the repository and reproduced my error. Apparently the _order_ of how the templates are provided matter for Ivy (to be honest, I did not know that). Placing the `loadingTemplate `_before_ the `treeNodeFullTemplate` solved my error. 

Something like this:
```
<tree-root #tree [nodes]="nodes" [options]="options">
  <ng-template #loadingTemplate>my custom loader</ng-template>
  <ng-template #treeNodeFullTemplate> [...] </ng-template>
</tree-root>
```

**Comment by tobiasengelhardt** [comment]
@Cowraider the order is not the important part. It's that they need to be seperate `ng-template` elements.
In the stackblitz the `loadingTemplate` is inside the `treeNodeFullTemplate` `ng-template`. If you move the `loadingTemplate` outside in the stackblitz there are also no errors when the `loadingTemplate` comes after the `treeNodeFullTemplate`.
