### ISSUE TITLE
how to add bullets to the child nodes 

### ISSUE THREAD

**Issue by satishchinthala** [CirclonGroup/angular-tree-component#860]
Hi , Please help me to add bullets to the child nodes in the tree structure

**Comment by tobiasengelhardt** [comment]
Hi @satishchinthala, do you want list like bullet points? Every node has a `tree-node-expander`, even the nodes without children. In there is a `span` with the `toggle-children-placeholder` class if there are no children. You can use that to style those like a list item.
Add this to your main `styles.scss`:
```
.toggle-children-placeholder {
  display: list-item;
  list-style-type: circle;
  list-style-position: inside;
}
```
You probably need to add some margin and padding to have the bullets in line, but this depends on your styling of the tree.
