### ISSUE TITLE
Property 'tree' does not exist on type

### ISSUE THREAD

**Issue by aplatov76** [CirclonGroup/angular-tree-component#872]
Hello, i do use simple filtering, but a have error:
`    
    ERROR in src/app/shared/modules/products/components/products/products.component.html:44:82 - error TS2339: Property 'tree' does not exist on type 'ProductsComponent'.
    
    44             <input type="text" class="form-control" id="filter" #filter (keyup)="tree.treeModel.filterNodes(filter.value)" placeholder="" aria-label="Text input with segmented dropdown button">
                                                                                        ~~~~
    
      src/app/shared/modules/products/components/products/products.component.ts:15:18
        15     templateUrl: './products.component.html',
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component ProductsComponent.
`

[component](https://gist.github.com/aplatov76/a3ccc29d935927ffb0b16305eb536670)
[template](https://gist.github.com/aplatov76/9a409fd11f055f7e188d20191364d4cb)

**Comment by kplatova97** [comment]
Problem is in <ng-template #treeNodeTemplate let-node let-index="index">

**Comment by kplatova97** [comment]
I did forgot added to input: *ngIf="nodes".
