### ISSUE TITLE
node_modules/@circlon/angular-tree-component/node_modules/mobx/lib/types/observableset.d.ts:21:22 - error TS2420: Class 'ObservableSet<T>' incorrectly implements interface 'Set<T>'.   Property 'toJSON' is missing in type 'ObservableSet<T>' but required in type 'Set<T>'.

### ISSUE THREAD

**Issue by somuda86** [CirclonGroup/angular-tree-component#882]
Building with angular 10 not working 
node_modules/@circlon/angular-tree-component/node_modules/mobx/lib/types/observableset.d.ts:21:22 - error TS2420: Class 'ObservableSet<T>' incorrectly implements interface 'Set<T>'.
  Property 'toJSON' is missing in type 'ObservableSet<T>' but required in type 'Set<T>'.
21 export declare class ObservableSet<T = any> implements Set<T>, IInterceptable<ISetWillChange>, IListenable {
                        ~~~~~~~~~~~~~

  node_modules/@types/core-js/index.d.ts:78:5
    78     toJSON(): any;
           ~~~~~~~~~~~~~~
    'toJSON' is declared here.

**Comment by somuda86** [comment]
@tobiasengelhardt is this a valid issue? Just curious here

**Comment by tobiasengelhardt** [comment]
Which version of the tree are you using?

**Comment by iamoku** [comment]
I have the same issue building with angular 11

**Comment by Adam-Michalski** [comment]
tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "skipLibCheck": true, --< add this line 
```

**Comment by somuda86** [comment]
Thanks @Adam-Michalski

**Comment by konstantinkrassmann** [comment]
Same problem here with angular 11. 
 `"skipLibCheck": true,` fixed it.
