### ISSUE TITLE
MR #887 left undesired logs.

### ISSUE THREAD

**Issue by liesahead** [CirclonGroup/angular-tree-component#889]
Noticed that there are some logs that wer eprobably left accidentally:

https://github.com/CirclonGroup/angular-tree-component/commit/f639c98fbd9faea1a950765ef8ad2c4bab507a6c

![image](https://user-images.githubusercontent.com/32300784/107937543-beac4e80-6f8c-11eb-8746-d4727c066e94.png)

**Comment by tobiasengelhardt** [comment]
@liesahead Thanks for that! Removed it and added `log` calls to the `no-console` linting so it does not happen again.
